MrcMorales\TyreBundle\Entity\SpeedRating:
    type: mappedSuperclass
    fields:
        value:
            type: string
            length: 255
        description:
            type: string
            length: 255
            nullable: true
