MrcMorales\TyreBundle\Entity\Tyre:
    type: mappedSuperclass
    fields:
        ean:
            type: bigint
            nullable: true
        name:
            type: string
            length: 255
        description:
            type: text
        sapCode:
            type: string
            length: 255
            nullable: true
        runflat:
            type: boolean
        fuelClass:
            type: string
            length: 255
        wetClass:
            type: string
            length: 255
        noise:
            type: integer
        noiseClass:
            type: string
            length: 255
        reinforced:
            type: boolean
        season:
            type: integer
        rollingResistance:
            type: integer
